source 'https://rubygems.org'

gem 'rails', '~> 6.1'
gem 'sqlite3'
gem 'puma'
gem 'whenever', :require => false
gem 'rexml'

group :development, :test do
  gem 'byebug'
end

group :development do
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'guard'
  gem 'guard-minitest'
end

group :test do
  gem 'timecop'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
