source 'https://rubygems.org'

gem 'rails', '~> 7.2'
gem 'sqlite3'
gem 'puma'
gem 'whenever', :require => false
gem 'rexml'
gem 'git'

group :development, :test do
  gem 'byebug'
end

group :development do
  gem 'guard'
  gem 'guard-minitest'
end

group :test do
  gem 'timecop'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

# No need for smtp stuff, but prod complains if I don't have this
# https://stackoverflow.com/a/70500221
gem 'net-smtp', require: false
gem 'net-imap', require: false
gem 'net-pop', require: false
