source 'https://rubygems.org'

gem 'rails', '5.2.1.1'
# Remove this sqlite3 restriction when we go to Rails >= 5.2.3
# see: https://stackoverflow.com/questions/54527277/cant-activate-sqlite3-1-3-6-already-activated-sqlite3-1-4-0
gem 'sqlite3', '~> 1.3', '< 1.4'
gem 'puma'
gem 'whenever', :require => false

group :development, :test do
  gem 'byebug'
end

group :development do
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'guard'
  gem 'guard-minitest'
end

group :test do
  gem 'timecop'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
